### ISSUE TITLE
Tests fail on GCC v5.4.0

### ISSUE THREAD

**Issue by simeks** [simeks/stk#6]
The tests for linux seems to fail on appveyor (GCC v5.4.0) and I'm not able to reproduce it on my machine (GCC v8.1.1) so I suspect there's some weird behaviour in GCC.

Expected exceptions thrown inside tests (inside `REQUIRE_TROW_AS`) seems to bypass the try-catch in the Catch2 macro. So rather than catching it (as expected) and move on, the application signals SIGABRT.

Did a small test based on the Catch2 macro:
```cpp
try {
    this_will_throw();
    catchAssertionHandler.handleUnexpectedExceptionNotThrown();
}
catch( exceptionType const& ) {
    catchAssertionHandler.handleExceptionThrownAsExpected();
}
catch( ... ) {
    catchAssertionHandler.handleUnexpectedInflightException();
}
```
and this will cause SIGABRT, without triggering any of the handle-functions.

I will leave the tests disabled for now and look more into this later.

**Comment by m-pilia** [comment]
I will have a look at this on my machine. gcc 5.4 is a couple years old, I guess it may be due to an incomplete implementation of C++17, or maybe to some bug somewhere...

Btw, I pushed a very small commit to master today, before realising of the development branch... Maybe we can merge the master again in the refactor branch.

**Comment by simeks** [comment]
I merged the master branch into the development branch now.
